
/*
    EXERCISE:
    Create multiple user registration classes for the following user types:
        - Customer
        - Seller
        - Admin
     All classes inherit from a base class "User"
     User contains => fullName, dob, gender, id(generated by method) and getters for these fields


     Customer will have customerId, balance, buy method and active flag
     Seller will have sellerId, list of goods(computers, food stuff, clothes, etc) and revenue and active flag
     Admin will have adminId and assigned list of customers and sellers, also method to suspend seller or customer


     Main class called 'Market'
 */

import java.util.Arrays;
import java.util.List;

public class Market {

    List<Customer> customers = Arrays.asList(
            new Customer(),new Customer()
    );

    List<Seller> seller = Arrays.asList(
            new Seller(),new Seller()
    );


    public static void main(String[] args) {

    }
}

        }